### ISSUE TITLE
I want to know all the possible phenomes espeak can output for language en

### ISSUE THREAD

**Issue by Bilal-Yousaf** [espeak-ng/espeak-ng#1213] opened 2022-06-11 13:06 UTC
Hi,

I am trying to calculate triphone coverage using espeack backend. For this I have to know out of all possible phenomes which are present in text and which are not.
I want to know all the possible phenomes espeak can output for language English (en).
Also I want to know, what stress phenomes (or other such phenomes which one should filter) espeak can output.

What is the best way to know this?

According to my research of this repository.
For English Espeak can output all possible phenomes mentioned (like this **phoneme i@**) in this file:
https://github.com/espeak-ng/espeak-ng/blob/master/phsource/ph_english

For stress words/phenomes I can take all such phenomes mentioned in the following file. And for languages main phenome list will change like for english we have ph_english for french we have ph_french but stress phenomes etc will remain same accross languages and are mentioned in following link:
https://github.com/espeak-ng/espeak-ng/blob/master/phsource/phonemes

Could you please confirm this? Or share a better way to do this? I might be totally wrong on this topic.

**Comment by jaacoppi** [comment] 2022-09-25 05:43
Closed as a duplicate of #1050

**Closed by jaacoppi** 2022-09-25 05:44 UTC
