### ISSUE TITLE
Typing interrupt doesn't work when using espeakup with espeak-ng

### ISSUE THREAD

**Issue by am-dxer** [espeak-ng/espeak-ng#285] opened 2017-06-28 12:15 UTC
I tried installing espeak-ng from git today to replace espeak in my Arch installation. I noticed that typing interupt is broken. AS an example, if I move by character quickly, espeak-ng finishes reading the last character before it starts reading the next one. I think that the problem is that the interupt actually happens but there is a delay. This is because if i read by line, the interupt happens but not right away. This works correctly in normal Espeak. I also installed pcaudiolib from git. I am not sure if the problem is there or in espeak-ng.

**Comment by valdisvi** [comment] 2017-06-28 12:30
Which audio system do you use (e.g. ALSA or Pulseaudio)?

**Comment by am-dxer** [comment] 2017-06-28 12:55
When i use espeakup, i use alsa. That is only  on my command line server systems. My understanding was that espeakup couldn't use Pulse because espeakup runs as a system service while pulse runs as the user. Is it possible to use espeakup with Pulse?

I would love to use Pulse if possible. I use Orca on my laptop with the gui and that uses Pulse and it works very well. When I tested espeak-ng with speech-dispatcher and pulse, it seemed to work fine.

**Comment by valdisvi** [comment] 2017-07-18 18:43
espeak-ng allows to use [Pulse by default](https://github.com/espeak-ng/espeak-ng#audio-output-configuration), but particular binary depends on configuration of distributed packages.
When I used Pulse with recent espeak-ng versions, I got [strange initialization errors](https://github.com/espeak-ng/espeak-ng/issues/278). Therefore now I'm using ALSA now.

**Comment by alex19EP** [comment] 2020-04-01 17:26
can not confirm on current espeakup and espeak-ng

**Comment by valdisvi** [comment] 2020-04-01 17:44
Which version are you using — 1.4x or 1.5x?

**Comment by alex19EP** [comment] 2020-04-01 18:37
@valdisvi 1.5x

**Comment by valdisvi** [comment] 2020-04-02 06:48
@am-dxer, then probably this issue can be solved by switching to the latest stable version of eSpeak NG.

**Comment by alex19EP** [comment] 2021-06-21 01:45
should we close this?

cannot reproduce on latest espeakup in Arch Llinux.

**Comment by valdisvi** [comment] 2021-06-22 08:16
@am-dxer, as per comment of @alex19EP, I'm closing this issue. If you can reproduce it, you can open it again.

**Closed by valdisvi** 2021-06-22 08:16 UTC
