### ISSUE TITLE
Arabic support

### ISSUE THREAD

**Issue by jasondiab** [espeak-ng/espeak-ng#891] opened 2021-03-12 09:43 UTC
Hello,
I tried both espeak-ng-20191129-b702b03-x64.msi and espeak-ng-20191129-b702b03-x86.msi
as well as building the project from the source code but the Arabic language isn't showing up in all cases. The build was successful but the Arabic language doesn't show up when I try to check "espeak-ng --voices"

**Comment by jaacoppi** [comment] 2021-03-12 12:09
Related to https://github.com/espeak-ng/espeak-ng/issues/864

The problem is that the Visual Studio project files and Wix installer files are incomplete. Someone with experience with Windows development should fix them - could you help?

Looks like this line is missing "ar":
https://github.com/espeak-ng/espeak-ng/blob/75ea4b0bdf158bfbbe982241942afaf5367cf80d/src/windows/data.vcxproj#L328

And this file is missing "ar_dict" (and parts of "ja_dict" for japanese:
https://github.com/espeak-ng/espeak-ng/blob/master/src/windows/installer/Product.wxs

Could you try to add support for arabic and japanese installers, and them explain how it's done so we can do it later if new languages are added?

**Comment by jasondiab** [comment] 2021-03-12 12:13
Thank you for your answer. I just saw the issue posted for the Japanese too. It seemed like copying and pasting the ja_dict and ja files to the right directories made it work. I was wondering where I could find the ar_dict file to try it out. Would be great if you could direct me on that end until we find a better fix.
I'm not very familiar with Windows development but I will try and take a look at it.

**Comment by jasondiab** [comment] 2021-03-12 12:42
Is there any other way to make it work without going through the installer? By building the project with some changes perhaps or any alternative that might've worked for you? @jaacoppi

**Comment by jaacoppi** [comment] 2021-03-12 14:58
Here's how I understand the build system. Hope this helps. My skills with Windows development are limited.

The main cause of the problem is that Linux and Windows separate build systems that are currently not synced with each other.

The build process is:

1. Build espeak-ng main program
In this step, the main program is built.

For linux the build system is called make and the configuration file is Makefile.am
For window the build system is Visual Studio (or msbuild for the command line version) and the configuration files are in src/windows/.

Currently everything is working fine for both linux and windows.

2. Build language data

In this step, espeak-ng is used with command line options --compile --compile-intonations and --compile-phonemes to produce the language files used. For example, arabic is --compile=ar and japanese is --compile=ja. The resulting files are espeak-ng-data/ar_dict and so on.

For linux the process works. For Windows, the build system is missing the commands to produce some of the _dict files. Apparently the missing lines are in src/windows/data.vcxproj but I'm not 100% sure.

For example, the rules for arabic seem to be missing, and ar_dict is not built. Rules for japanese are ok and ja_dict is build.

Someone should go through the Visual studio project files either by hand or with Visual Studio and see that each language mentioned in docs/languages.md is built correctly.

In the long term, this should be done whenever a new language is added to make sure this doesn't happen to other languages. I'm sorry to say that windows support has not been a high priority. It's not because we don't want to, it's because we don't know how.


3. Create the installer package

For linux, the command make install is used to install the program. Most linux distributions also have a package management system that packages the right files.

For Windows, WiX installer is used to package the files into an .msi file that is used for installing. This step is also missing some languages. 

Someone should go through the Wix installer files like src/windows/installer/Product.wxs and see that an installation instruction is created for each language built in step 2.

**Comment by rhdunn** [comment] 2021-03-24 17:22
@jaacoppi Yes, that summary looks correct.

**Comment by rhdunn** [comment] 2021-03-24 18:10
I've pushed a fix for the two issues here, and am looking at extending the tests that they add to check that nothing has been omitted.

**Closed** 2022-04-02 19:02 UTC
Labels: build, good first issue
