### ISSUE TITLE
Two and three letter words within emoji keywords are spelled out

### ISSUE THREAD

**Issue by pvagner** [espeak-ng/espeak-ng#471] opened 2018-04-26 12:11 UTC
Hello,
I have just noticed that all two and three letter words inside the emoji keywords are spelled letter by letter rather than being read continously as a word. This is with slovak (sk) language.
What's the best method to fix this? Shal I edit sk_emoji file by hand or does this require adjustments to the CLDR parsing?
These are all the two letter and three letter pronouns, nouns, prepositions, conjenctions and foreign words I have noticed inside the sk_emoji file:
sa
od
si
so
bez
úst
oči
ale
na
je
zle
zlo
muž
nad
vo
za
dve
pár
ťa
nos
oko
chr
mám
reč
šál
rúž
psa
pes
kôň
býk
myš
jež
had
kus
nôž
dom
noc
pri
loď
pol
tri
päť
nov
spln
pás
kôš
luk
šíp
ako
aj
top
óm
jin
váh
rýb
pre
sto
cool
free
new
nie
man
srílanka
jan
san
da
čad

**Comment by jaacoppi** [comment] 2018-04-26 13:36
Looks like a problem in the code. No need to edit the sk_emoji file.

Just to be clear, is this right:

```
espeak-ng -v sk "smejúca sa tvár" -x
 sm'eju:tsa sa tv'a:R
```

..And is this wrong:
```
espeak-ng -v sk "☺" -x
 sm'eju:tsa s'a tv'a:R
```

I can't confirm this in english but I'll keep digging.

**Comment by pvagner** [comment] 2018-04-26 14:31
Hello,

Unfortunatelly this appears to be more complicated.
By verifying your command line examples I have realized the issue only occurs if emoji is surrounded by another text.

For example this is correct:
```
$ espeak-ng -v sk "blah smejúca sa tvár blah" -x
 bl'ax sm'eju:tsa sa tv'a:R bl'ax
```
And this one is wrong
```
$ espeak-ng -v sk "blah ☺ blah" -x
 bl'ax sm'eju:tsa 'es,a: tv'a:R bl'ax
```

Please notice how the word sa is being translated into [sa] in the first call and incorrectly how word sa is translated into ['es,a:] in the second case.

Does it make sense now?

**Comment by jaacoppi** [comment] 2018-04-26 15:00
it makes sense now. With my examples "sa" was stressed differently but pronounced correctly. With your examples it's clear that the word is spelled letter by letter.

I'll post here once I figure out why this is happening. The reason is probably in ReadClause() or TranslateClause().

**Comment by jaacoppi** [comment] 2018-04-26 15:44
This code gets executed with "blah ☺ blah":
https://github.com/espeak-ng/espeak-ng/blob/e40380260eb22f569e87128ccd3446df795d68b5/src/libespeak-ng/translate.c#L717-L726

Next step is figuring out where those flags and variables are set and why. The comments don't make sense in this case.

**Comment by pvagner** [comment] 2018-04-26 18:09
I went through sk_list and sk_rules trying to find out if there is something common for the words I have put in the original report.
We do have some of them listed with $u flag such as some prepositions an conjunctions. However not all of them are part of these rules. So the only bit that matters is most likelly the code you have pointed to.
Anyway the only bit that is clear for me by reading that code is that it matches two and three letter words.
I assumed number of words written in lower case within a clause also does matter however I have tried extending the failing example command line with more words including upper case words and it's failing all the time for me.
I imagine this might be happening for more languages (at least all the slavic languages I guess).

**Comment by jaacoppi** [comment] 2018-04-26 19:11
My best guess is int all_upper_case (which is set to FLAG_ALL_UPPER) and this line:
https://github.com/espeak-ng/espeak-ng/blob/e40380260eb22f569e87128ccd3446df795d68b5/src/libespeak-ng/translate.c#L2441

It seems that for some reason FLAG_ALL_UPPER is set for  `words[index containing the emoji].flags`,  causing the code I posted earlier to execute.

**Comment by pvagner** [comment] 2018-04-27 06:32
Oh, I'm sorry but I don't know how can I tweak this in order to verify or do something else that might be usefull at this point.
Can you propose a change or give me some more hints?

**Comment by jaacoppi** [comment] 2018-04-27 09:48
You could trace where `wflags` is set with `FLAG_ALL_UPPER` and why this happens only
1) for the emoji and not to all words in `words[]`
2) when there's other text in the same buffer with the emoji

I think we now have enough information to locate the bug and more verification is not needed at this point. It will simply take some time to find the actual reason for this.

**Comment by rhdunn** [comment] 2018-04-27 12:05
Looking through the code:
1.  `all_upper_case` is set to `FLAG_ALL_UPPER` by default: https://github.com/espeak-ng/espeak-ng/blob/e40380260eb22f569e87128ccd3446df795d68b5/src/libespeak-ng/translate.c#L1961
2. It is only cleared when the character is an alphabetical character (`IsAlpha`) and the character is not upper case. https://github.com/espeak-ng/espeak-ng/blob/e40380260eb22f569e87128ccd3446df795d68b5/src/libespeak-ng/translate.c#L2321

A possible fix:
1.  Keep a count of the number of alphabetical characters seen (`alpha_count`, initialised to 0).
1.  Increment in the `IsAlpha` branch: https://github.com/espeak-ng/espeak-ng/blob/e40380260eb22f569e87128ccd3446df795d68b5/src/libespeak-ng/translate.c#L2235
1.  Reset `alpha_count` to 0 along with `all_upper_case in https://github.com/espeak-ng/espeak-ng/blob/e40380260eb22f569e87128ccd3446df795d68b5/src/libespeak-ng/translate.c#L2470
1.  Before setting `flags`, clear `FLAG_ALL_UPPER` if `alpha_count` is 0 (`if (alpha_count == 0) all_upper_case &= ~FLAG_ALL_UPPER;`). https://github.com/espeak-ng/espeak-ng/blob/e40380260eb22f569e87128ccd3446df795d68b5/src/libespeak-ng/translate.c#L2441

**Comment by rhdunn** [comment] 2018-04-30 06:12
Thanks for helping investigate the cause of this issue. I have now pushed a fix, as I outlined above.

**Closed by rhdunn** 2018-04-30 06:12 UTC
