### ISSUE TITLE
Android release doesn't work

### ISSUE THREAD

**Issue by Ghostbird** [espeak-ng/espeak-ng#974] opened 2021-06-29 19:10 UTC
I recently installed the F-Droid release of eSpeak, version 1.51-dev.20. However it was unusable because of these issues:

- No voices are installed
- Import eSpeak dictionary setting doesn't work
- eSpeak is selectable in Android Text-to-speech output, but tapping it, will not select it, even though the "ripple" effect plays.

Any idea what I can do to solve this?
![Screenshot_20210629-210855_1](https://user-images.githubusercontent.com/1202149/123854006-a0c50200-d90d-11eb-92a9-55c946976543.png)

**Comment by Ghostbird** [comment] 2021-06-30 08:52
Never mind, it must be something with my system. The non-free release on the Play Store has exactly the same issue, and it's a different version.

**Comment by SohnyBohny** [comment] 2021-07-22 13:18
I'm experiencing exactly the same issue. Have you been able to solve it?

**Comment by Ghostbird** [comment] 2021-07-22 14:58
Alas no, I've installed Google's TTS for now.

**Comment by Ruthalas** [comment] 2021-09-05 21:29
This issue still persists, and it'd be great if the f-droid release were functional. Should a new ticket be submitted for this issue?

**Comment by Ghostbird** [comment] 2021-09-10 06:42
It might be a good idea to open a new issue that describes the exact problem. I opened this with the wrong assumption that it was an issue with the F-Droid build, but maybe it's a code issue.

**Comment by vanMacG** [comment] 2021-11-17 08:11
I have the same issue... any information how to set it up?

**Comment by Ghostbird** [comment] 2021-12-13 20:05
I think @Ruthalas didn't open a new issue. Maybe a new issue should be opened. Note that the problem is _not_ with the F-droid release. The Play Store release had the same issue for me. I have used Google TTS instead of espeak-ng, though I would have preferred to use espeak. I have used espeak-ng to good effect on Raspberry Pi in the past.

**Comment by alex19EP** [comment] 2021-12-13 23:20
hello all. I preparing a espeak-ng release to playstore of course free and without adds.
you can email me your gmail address at email at alix19ep.me
and I will add you to private beater.

**Comment by lpstandardrp** [comment] 2021-12-17 07:51
@alex19EP Thank YOU! Can't wait!!

**Comment by alex19EP** [comment] 2021-12-17 10:08
> @alex19EP **Thank YOU!** Can't wait!!
> 
> Edit: Your message wasn't delivered to 
> email at alix19ep.me 
> because **the domain alix19ep.me couldn't be found.** Check for typos or unnecessary spaces and try again.
> 
> Should there be a symbol between the 9 and ep? (**alex19 [at] ep.me** ?)

Yes at meens@

**Comment by paolo-caroni** [comment] 2022-02-19 23:01
Honestly I have problem for set espeak as default engine, but then it run on android 9 on a samsung galaxy S5 mini and android 11 on Fairphone 3+ (lineageos ROM on both case).

**Comment by archtur** [comment] 2022-03-28 19:52
> hello all. I preparing a espeak-ng release to playstore of course free and without adds. you can email me your gmail address at email at alix19ep.me and I will add you to private beater.

Hi @alex19EP,

I'm having exactly the same issue. I have only tested the `1.51-dev` version from f-droid, but espeak-ng is completely unusable.

I`m not able to give you a gmail addresse, because I don't have one. :)
Couldn't you deliver the fixed version to f-droid repository?

**Comment by alex19EP** [comment] 2022-03-28 20:01
hello.

> Couldn't you deliver the fixed version to f-droid repository?

I'm not very familiar with fdroid, but I'll try it one of these days.

**Comment by vanMacG** [comment] 2022-03-28 20:25
@archtur I recently got it to work. I try to give a step-by-step explanation:

- Install espeak 1.51-dev from f-droid
- start espeak - click on three-dot-menu in the upper right - 2nd entry "general TTS settings"
- This will bring you to general android speech-setting - click on "preferred modul" and select "espeak" - accept warning "ok"
- this will trigger download/initialisation of system language - click on back
- now you are back in espeak overview and "default voice" is set to your system language
- (if you want another language: go to general android speech-settings - change language - this will change the language in espeak)

I hope this helps.

**Comment by archtur** [comment] 2022-03-29 13:18
Thank you @alex19EP for your fast response.

The steps from @vanMacG worked also on my system.
Which of the steps inside @vanMacG s description will then be easier?
I will wait for that f-droid update, install it freshly and tell you what changed.

If you think you don't have to change something, maybe it would be good to describe the steps the user has to take to make it run directly inside the espeak application. Then it wiould be easier for the user to get it running.

The fact that espeak-ng is usable will help most German lineageos users out of their missing-tts-misery, I hope (see [lineageos 16 thread from 2019/2020](https://forum.kuketz-blog.de/viewtopic.php?t=3401) and [lineageos 18 thread from 2021/2022](https://forum.kuketz-blog.de/viewtopic.php?t=8110)). Until now espeak would be the only solution for open source tts on android I you need German.

Speech Services by Google  is the only solution at the moment. But 
1. not open source
2. Google software (which some people like me try to avoid/escape)
3. and not working (cannot download language files for offline usage)

Thank you in advance. I'm looking forward to this release.
Thank you @vanMacG also for your help!

**Comment by akostadinov** [comment] 2022-07-04 08:53
Any updates?

**Comment by alex19EP** [comment] 2022-07-04 09:43
Duplicate of #1078

**Closed by alex19EP** 2022-07-04 09:43 UTC
