### ISSUE TITLE
please add sapi5 in espeak Haitian Creole

### ISSUE THREAD

**Issue by weatherchann** [espeak-ng/espeak-ng#514] opened 2018-07-04 13:15 UTC
please add sapi5 in eSpeak NG Haitian Creole

**Comment by weatherchann** [comment] 2018-07-04 13:22
Help me

**Comment by weatherchann** [comment] 2018-07-04 20:38
@rhdunn please respond me

**Comment by rhdunn** [comment] 2018-07-04 21:13
You don't need to consistently bug people, especially after only 8 hours.

Duplicate of #7.

**Closed by rhdunn** 2018-07-04 21:13 UTC
