### ISSUE TITLE
Handling symbols by Espeak

### ISSUE THREAD

**Issue by Gushasad** [espeak-ng/espeak-ng#210] opened 2017-02-01 15:44 UTC
Hello,
I have a suggestion: Can espeak handle symbols? I would like to make it read emoticons and emoji onLinux, but I cannot, due to its inability to handle symbols. Developers, please look at that, because this could be verry helpful for some users... I can add emoticons and emoi, just allow me to.

**Comment by rhdunn** [comment] 2017-02-01 18:25
Duplicate of #16.

**Closed by rhdunn** 2017-02-01 18:25 UTC
