### ISSUE TITLE
Voice Chinese (Mandarin): some characters are reported two times

### ISSUE THREAD

**Issue by surfer0627** [espeak-ng/espeak-ng#685] opened 2019-12-03 03:29 UTC
Some characters are reported two times, E.G. 汐止區 (reported: 汐止止區)

### Steps to reproduce:
1. Open [eSpeak NG testing page](https://odo.lv/Espeak?language=en).
2. Choose language Chinese (Mandarin).
3. Test:

汐**止**區
貸**款**
媒**體**
國立臺**北**教育大學
瀏**覽**模式
徵**聘**
註**解**
矯**正**機關
徵**收**
紓**解**
恭**喜**
鬆**綁**
拓**展**
澄**清**

**Comment by materia-cccp** [comment] 2020-01-31 15:40
Duplicate somewhere

**Comment by jaacoppi** [comment] 2020-07-16 10:34
This works:
_espeak-ng -X -v zh 你好_

```
Replace: 你   ni3
Translate 'ni3'
  1     n        [n]

  1     i        [i]

 22     3        [214]

Replace: 好   hao3
Translate 'hao3'
  1     h        [X]

  1     a        [A]
 22     ao       [Au]

 22     3        [214]

n'i35_| X'Au214_|




```
This is wrong. The second word is interpreted twice: first as a part of the first word, then as a standalone word:
_espeak-ng -X -v zh 貸款_

```
Replace: 貸 款   dai4kuan3
Translate 'dai4kuan3'
  1     d        [t]

  1     a        [A]
 22     ai       [ai]

 22     4        [51]

  1     k        [kh]

  1     u        [u]
 86     k) ua (DnK [wa]
 22     ua       [wA]
 65     ua (DnK  [ua]

  1     n        [n]

 22     3        [214]

Replace: 款   kuan3
Translate 'kuan3'
  1     k        [kh]

  1     u        [u]
 86     k) ua (DnK [wa]
 22     ua       [wA]
 65     ua (DnK  [ua]

  1     n        [n]

 22     3        [214]

tai51khw'a35n_| khw'a214n_|

```

Most likely this is a unicode/multibyte issue. Some characters aren't separated properly. I wonder why it only affects certain characters. Anyone have any ideas or should I keep digging?

**Comment by jaacoppi** [comment] 2020-07-16 11:46
Did some digging. This is a duplicate of #606.

**Closed** 2022-09-25 08:54 UTC
