### ISSUE TITLE
Japanese language cannot read Japanese characters and numbers

### ISSUE THREAD

**Issue by Fatihyuksek** [espeak-ng/espeak-ng#498] opened 2018-05-31 23:12 UTC
The Japanese language cannot read most of the Japanese characters and it cannot read the numbers in Japanese either. When in a text with numbers it ignores the numbers and it cannot read most of the Japanese characters as I said before. Also it spells the latin characters, reading a word written in latin characters letter by letter.

**Comment by jaacoppi** [comment] 2018-06-02 07:29
See https://github.com/espeak-ng/espeak-ng/issues/366. Does this help in any way?

It seems the numbers are not included in the file dictsource/ja_list and latin characters are not include in ja_rules. These should be added. Are you proficient in japanese to add the correct pronunciation? We can help with the technical side of it. See dictsources/zh_list for an example of how numbers are written.

**Comment by Fatihyuksek** [comment] 2018-06-02 11:03
Hello,
Sorry, I am not proficiant in Japanese language. I jus want to play sone audio games in Japanese.

iPhone’umdan gönderildi

jaacoppi <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (2 Haz 2018 10:29):


See #366<https://github.com/espeak-ng/espeak-ng/issues/366>. Does this help in any way?

It seems the numbers are not included in the file dictsource/ja_list and latin characters are not include in ja_rules. These should be added. Are you proficient in japanese to add the correct pronunciation? We can help with the technical side of it. See dictsources/zh_list for an example of how numbers are written.

**Comment by rhdunn** [comment] 2018-06-07 12:35
Duplicate of #366.

**Closed by rhdunn** 2018-06-07 12:35 UTC
