### ISSUE TITLE
Make a release to fix #338

### ISSUE THREAD

**Issue by jiangtiandao** [espeak-ng/espeak-ng#448] opened 2018-04-02 11:08 UTC
In most recent release 1.49.2 Chinese Mandarin voice is totally unrecognizable.
Though #338 was fixed in Nov. 2017 this fix wasn't included in a stable version.
which kept NVDA from merging the fix into its release.
Would you please release a new stable version containing this fix? 
If that  disrupt project roadmap  or something similar.Would you please make a hotfix release based on 1.49.2 then only cherry pick that commit to avoid other issues affecting stability?

**Comment by vgjh2005** [comment] 2018-04-03 04:34
I think so!

**Comment by man0528** [comment] 2018-04-11 12:12
I think it is very necessary. It's very urgent, too.

**Comment by Porges** [comment] 2018-04-19 11:38
Would this be the cause of my problem here? https://github.com/nvaccess/nvda/issues/8185#issuecomment-381854507

**Comment by jiangtiandao** [comment] 2018-04-20 08:51
@Porges  Since next version of NVDA use espeak-ng on master branch
you can test with next version and determine whether this issue is related to #338

**Comment by valdisvi** [comment] 2020-04-13 16:55
With [1.50](https://github.com/espeak-ng/espeak-ng/releases/tag/1.50) this should be fixed.

**Closed by valdisvi** 2020-04-13 16:55 UTC
