### ISSUE TITLE
fix the intonation of question marks when finishing a question in Latin Spanish

### ISSUE THREAD

**Issue by gregodejesus** [espeak-ng/espeak-ng#1325] opened 2022-09-01 09:01 UTC
by default, espeak ng does not intone at the end of a question, it is as if it contained a comma
here I leave the file to be added
[Spanish (Latin America).zip](https://github.com/espeak-ng/espeak-ng/files/9468426/Spanish.Latin.America.zip)

**Comment by jaacoppi** [comment] 2022-09-01 16:32
Is this a duplicate of #1313 ?

**Closed** 2022-10-16 21:25 UTC
