### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [espeak-ng/espeak-ng#1033] opened 2021-10-29 22:09 UTC
I think that it would be good to flush currently committed changes and make new release :)

**Comment by jaacoppi** [comment] 2021-11-02 03:38
Duplicate of #857.

**Comment by valdisvi** [comment] 2022-04-02 19:47
Enjoy: https://github.com/espeak-ng/espeak-ng/releases/tag/1.51

**Closed by valdisvi** 2022-04-02 19:47 UTC
