### ISSUE TITLE
Feature Request: Port eSpeak NG to iOS 16, and expose it to VoiceOver using AVSpeechSynthesisProviderAudioUnit.

### ISSUE THREAD

**Issue by robin24** [espeak-ng/espeak-ng#1291] opened 2022-08-17 23:37 UTC
## Summary

iOS 16 Beta introduces [AVSpeechSynthesisProviderAudioUnit](https://developer.apple.com/documentation/avfaudio/avspeechsynthesisprovideraudiounit), which should enable the integration of 3rd-party speech synthesizers into the VoiceOver screenreader, as well as Speak Screen and other assistive features that rely on speech synthesis.
With this in mind, it would be awesome if eSpeak NG, given its strong popularity within the screenreader community, could be ported to iOS and macOS.

## Steps required to make this work

As far as I can tell, three main steps would be required to pull this off, with step 1 and 2 probably being the most work intensive:
1. Port eSpeak NG to iOS - I've actually tried my hand at this, but don't know enough about C to fix all the compiler issues.
2. Write a wrapper to make the ported version of eSpeak NG conform to AVSpeechSynthesisProviderAudioUnit.
3. Build a simple SwiftUI app to manage active voices, and perhaps manage dictionaries that could be loaded directly into the synthesizer.

**Comment by XP-Fan** [comment] 2022-09-09 15:51
Well please! Seriously I'll give 100 € (via PayPal), to the dev who makes this a reality provided he/she also manages to include the NVDA variants and the Libsonic or what it was called, so I can finally bring my iPhone's VoiceOver speech on par with the speed and low latency of my Windows XP computers.

**Comment by TheQuinbox** [comment] 2022-09-13 02:53
Hi @robin24,
How were you testing building this for iOS? I just built for Mac and it built flawlessly, and works. Should we get a basic AVAudioSpeechSynthesisUnitProvider working on MacOS Ventura (assuming it supports it), and then port it to iOS?

**Comment by parhamdoustdar** [comment] 2022-09-13 08:22
I'd certainly appreciate espeak on MacOS very much.

**Comment by robin24** [comment] 2022-09-13 10:51
Hey @TheQuinbox!

That's super cool, how did you get that to work?
I tried to approaches both of which failed for me:

1. I followed the instructions for building on Linux / Mac / BSD found here, installing necessary dependencies via Homebrew:
https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md
For me that resulted in lots of compiler warnings / errors when running the make command, chances are this is because I'm on an M1 machine, are you on Intel or M1 as well?
2. I also tried building with Xcode by following the instructions in this blog post: https://calebschoepp.com/blog/2021/compiling-espeak-ng-in-xcode-for-ios-app/.
Unfortunately I got stuck with various errors suggesting that various files couldn't be located, but honestly this could be user error on my end as I've never tried anything like this in Xcode.

Getting this to work on macOS first sounds like the best approach though, as building for iOS probably requires some sort of cross compilation, I believe Xcode can do this or perhaps cmake on the command line as well, but that's probably a lot more involved I suppose.

**Comment by TheQuinbox** [comment] 2022-09-13 15:26
Hi @robin24,
I did the following:

1. git clone --recursive espeak-ng/espeak-ng
2. cd espeak-ng
3. ./autogen.sh
4. ./configure --prefix=/usr
5. brew install automake
6. make

I got a functional espeak lib that talks!

**Comment by XP-Fan** [comment] 2022-10-16 21:03
Any progress with this? Having ESpeak with VoiceOver on iPhone would be a gamechanger for many blind people.

**Comment by nidza07** [comment] 2022-10-16 23:09
Hello,
I definitely also hope this can eventually happen.
For anybody interested to work on it, Apple has recently published documentation on how to use the new API to create a speech synthesizer:
https://developer.apple.com/documentation/avfaudio/audio_engine/audio_units/creating_a_custom_speech_synthesizer?language=objc

**Comment by mjonsson1986** [comment] 2022-10-19 10:19
sinz the creator dont care about sapi. the hopes are small

**Comment by XP-Fan** [comment] 2022-10-19 17:40
What does this have to do with sapi?

Von: mjonsson1986 ***@***.***
Gesendet: Mittwoch, 19. Oktober 2022 12:20
An: espeak-ng/espeak-ng ***@***.***>
Cc: XP-Fan ***@***.***>; Comment ***@***.***>
Betreff: Re: [espeak-ng/espeak-ng] Feature Request: Port eSpeak NG to iOS 16, and expose it to VoiceOver using AVSpeechSynthesisProviderAudioUnit. (Issue #1291)


sinz the creator dont care about sapi. the hopes are small

**Comment by djphoenix** [comment] 2022-10-25 21:25
I can contribute to this issue and provide iOS/macOS framework that wraps espeak-ng into AVSpeechSynthesisProviderAudioUnit. But, for sure, espeak-ng is GPL-licensed, so somewho should open and maintain entire project source, including wrapper and configuration UI. And so maintain AppStore release if and when it come out officially.

**Comment by XP-Fan** [comment] 2022-10-25 21:52
Well yeah, please, please please do: I’m waiting for ESpeak ever since the first day I do have an iPhone. Seriously: All the commercial stuff out there (at least those things whose ship with Apple devices) just can’t get fast enough for me to be able to sanely work with… Well yeah right we also need some basic configuration UI so that I can set it to the NVDA variant and enable the additional speedboost.

**Comment by djphoenix** [comment] 2022-10-27 10:02
The first attempt to build swift package with libsonic and libespeak-ng [was successful](https://user-images.githubusercontent.com/1833493/198255383-9692d526-ac4c-437a-ba1d-595497189b61.png). Let's start a wrapper.

**Comment by XP-Fan** [comment] 2022-10-27 12:04
Sounds promising, thank you very much in advance, it’s really appreciated. I’m looking forward…

**Comment by djphoenix** [comment] 2022-10-28 15:44
Looks like test app working. Will upload initial version after some cleanup...

![image](https://user-images.githubusercontent.com/1833493/198678517-28418706-339d-4af6-979f-f9a474836e33.png)

**Comment by mjonsson1986** [comment] 2022-10-28 15:54
You meen espeak voiceover compatible? Skickades från E-post för Windows Från: Yury PopovSkickat: den 28 oktober 2022 17:44Till: espeak-ng/espeak-ngKopia: mjonsson1986; CommentÄmne: Re: [espeak-ng/espeak-ng] Feature Request: Port eSpeak NG to iOS 16, and expose it to VoiceOver using AVSpeechSynthesisProviderAudioUnit. (Issue #1291) Looks like test app working. Will upload initial version after some cleanup...—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by XP-Fan** [comment] 2022-10-28 17:21
mjonsson1986 Your message is not readable on a plain email client. I do see Office HTML like sourcecodes.

**Comment by mjonsson1986** [comment] 2022-10-28 17:30
@ XP-Fan thats because i answer by email in thunderbird

**Comment by djphoenix** [comment] 2022-10-28 17:35
> and your paypal if it works.


I not do it for money but for idea. Open source software should **help** people. I have received many messages with thanks from blind people, it's unusual, it's... pleasant?)

If it does matter, send a donation to any fund (medical on open-source) for your choice.

**Comment by mjonsson1986** [comment] 2022-10-28 17:39
please give me an test flight link when it is ready

**Comment by djphoenix** [comment] 2022-10-28 17:40
> please give me an test flight link when it is ready

Of course

**Comment by mjonsson1986** [comment] 2022-10-28 17:41
eh? i assume this is for mac too?

**Comment by XP-Fan** [comment] 2022-10-28 18:39
You are an awesome man.

**Comment by robin24** [comment] 2022-10-28 23:01
Hey,

Sorry I haven't commented here for a while, been busy job hunting and so I needed to put this on the back burner for some time.
@djphoenix Wow, thanks so much for taking this up! Your progress with this sounds really awesome, I'd be more than happy to join in on helping with the wrapper and developing a SwiftUI interface for setup and config if you like.
I somehow failed to get this to build on my M1 machine even with @TheQuinbox's instructions, but it sounds like you were able to wrap this inside of a Swift package so hopefully I'll have more luck with that.

Thanks again for your wonderful work Yuri and I hope we get to work together on this cool project.

**Comment by djphoenix** [comment] 2022-10-29 10:43
@robin24 welcome back)

Sure, I will share the library wrapper and app code in next days.  I'm not sure for M1 macs, but there are nothing to fail because it builds on iPhoneSDK.

**Comment by djphoenix** [comment] 2022-10-30 10:23
OK now swift package seems stable with latest master, so I released it [here](https://github.com/djphoenix/espeak-ng-spm). The application is still in progress, because when I published all available voices/langs to VoiceOver, Settings app on my iPhone is stuck for ~10s trying display it all, and iPhone becomes a grill. Need to add some configuration UI to select a part of languages...

**Comment by mjonsson1986** [comment] 2022-10-30 10:29
unsure how to download it? or should i clone the git and compile?

**Comment by djphoenix** [comment] 2022-10-30 10:33
@mjonsson1986 i’m unsure that I understood your question. There’s no app/UI, only library. It is available as Swift Package in XCode.

**Comment by mjonsson1986** [comment] 2022-10-30 11:09
if i will test espeak with voiceover with this. how to do?

**Comment by djphoenix** [comment] 2022-10-30 12:06
> how to do?

Nothing to do now. Be patient a bit and wait for app. It is on the way)

**Comment by djphoenix** [comment] 2022-10-30 14:57
Good news - app is uploaded to TestFlight and waiting for review and approval by Apple.

**Comment by robin24** [comment] 2022-10-30 17:20
@djphoenix wow, amazing news!

Is your code already in a public repo somewhere?
Would love to build this locally to give it a spin, also curious to see what you did to get Xcode to build all the libraries - like I said this is something I've never done before personally so this makes for a great learning opportunity :-).

**Comment by djphoenix** [comment] 2022-10-30 17:29
@robin24 of course, all code is open now.
See https://github.com/espeak-ng/espeak-ng-ios-app and https://github.com/espeak-ng/espeak-ng-spm repositories.

**Comment by mjonsson1986** [comment] 2022-10-30 17:54
hope the app can be running on both mac and ios?

**Comment by djphoenix** [comment] 2022-10-30 18:26
It work on macOS, but only since 13.0 which supported with XCode 14.1. Unfortunately it is not released yet, it is still RC2. I can't install it because I need production (stable) environment on small macbook SSD...

I will test and release macOS app as xcode 14.1 release happens.

**Comment by mjonsson1986** [comment] 2022-10-30 18:41
why release 2 separate apps?  mac os 11 and above can runios apps.. or do you meen 2 separate: 1 for m1 mac and ios. and 1 for intel maybe

**Comment by djphoenix** [comment] 2022-10-30 18:44
@robin24 I think that this is because `app groups` that needed to exchange data between app and extension. Try to change identifiers and recover signing via xcode.

**Comment by djphoenix** [comment] 2022-10-30 18:47
> why release 2 separate apps? mac os 11 and above can runios apps.. or do you meen 2 separate: 1 for m1 mac and ios. and 1 for intel maybe

I'm not sure how iOS app extension will work on macOS. Also Intel macs are wide used. And I think that separate app is better anyway.

**Comment by robin24** [comment] 2022-10-30 18:50
@djphoenix Right, what's weird though is I already did that and set up the app groups for the main app as well as the extension, yet I keep running into this entitlement error...
I've already tried making a clean build and cleaning out my derrived data folder without any luck, I'll keep digging then.

**Comment by djphoenix** [comment] 2022-10-30 19:02
Make sure to update UserDefault's ID according to your app group

**Comment by robin24** [comment] 2022-10-30 19:22
@djphoenix Ah yes, found the issue!

There are a couple hardcoded references to "group.dj.phoenix.espeak-ng" in the code, once I changed them for my group identifier it all worked as expected, awesome!!!

It would probably be best to change that code to construct the correct ID from the current bundle identifier at runtime so that it doesn't need to be changed manually when someone other than you wants to build this locally, I can take a look at that.

**Comment by djphoenix** [comment] 2022-10-30 19:28
> There are a couple hardcoded references… It would probably be best to change that code…

K’mon, guys, that’s first working version, and make it work well is long roadmap. Keep in mind that it’s one week old. Of course I will clean it up and update.

**Comment by djphoenix** [comment] 2022-10-30 19:34
That becomes a chat… since we have separate repository with iOS app, maybe we should move a discussions to its “issues”, right?

**Comment by robin24** [comment] 2022-10-30 20:07
@djphoenix Sorry, I wasn't trying to come across as impatient or criticizing your work in any way, only pointed this out because it's somewhat hard to catch when building the project for the first time, plus the debugger isn't helpful either in this case and just shows an entitlement error without much context.

I think it's really impressive how far this has come in a super short time, even including support for all the languages and voices that the synthesizer supports as far as I can tell.

Also you're right that we should move further discussion to the new repos, let's maybe keep this one around until the TestFlight submission is approved so we can share the link with everyone following along.

Again, sorry for the misunderstanding!

**Comment by djphoenix** [comment] 2022-10-30 20:11
Oh, of course all OK. My english isn't perfect, and I never want to offend anyone. We all are doing the things to get the open world better.

**Comment by djphoenix** [comment] 2022-10-30 22:26
Let the show begin.

https://testflight.apple.com/join/Q3zQlq47

**Comment by codeofdusk** [comment] 2022-10-31 00:34
> Let the show begin.

Wow, that's great! @jwoo-msft and I tried our hand at porting this a while back. We got it running in a test app (as you did) but didn't get the system/VoiceOver integration going.

I've installed your testFlight app, but eSpeak doesn't appear in VoiceOver settings. Is it supposed to at this point?

**Comment by nidza07** [comment] 2022-10-31 00:37
@codeofdusk I had exactly the same issue as you at first, but I did the following and that caused it to appear.
First of all, I of course opened the ESpeak NG app and accepted the TestFlight warnings/activated the start testing button.
I assume you did that already, but it still didn't appear for me.
However, I restarted my phone, and then it appeared in VoiceOver settings.
You should see it under any language that is supported, there should be an ESpeak NG section with all the variants.

There are some bugs I will report later after additional testing, but globally, this is awesome! Thanks so much @djphoenix

**Comment by codeofdusk** [comment] 2022-10-31 00:45
@nidza07 I've tried rebooting several times, but it still isn't displayed.

**Comment by nidza07** [comment] 2022-10-31 01:06
Sorry that didn't help, you must be running into a different problem in that case. The only thing worth pointing out is that the API is iOS 16 exclusive, but I am assuming you're already aware of that.

Hopefully a solution is found...

**Comment by nidza07** [comment] 2022-10-31 01:31
It seems that this is indeed currently a little buggy. After using it for a while, my ESpeak also completely disappeared, but for me it was enough to open the ESpeak NG app again and it appeared once more.

**Comment by mjonsson1986** [comment] 2022-10-31 02:38
when will the mac version come?

**Comment by mjonsson1986** [comment] 2022-10-31 04:59
this app installs on m1 mac. but no voices show up in voiceover

**Comment by djphoenix** [comment] 2022-10-31 05:31
@mjonsson1986 keep patient for a bit, I think xCode 14.1 will be released in this week, and I complete a port.

**Comment by djphoenix** [comment] 2022-10-31 05:33
@codeofdusk @nidza07 here a some bugs of course, and I have caught your issue with missing voiceover... once. I can't reproduce and so debug it...

I think a lot of bugs will disappear after code cleanup and refactoring.

**Comment by djphoenix** [comment] 2022-10-31 05:57
I notes all discussions in iOS project issues. As TestFlight available now, I think that we may close this one.

**Closed** 2022-10-31 07:05 UTC
Labels: feature, portability

**Comment by willwade** [comment] 2024-01-04 23:29
Nudge: its been done but I can't see this in the current live version of the app.. just saying - it would be helpful if someone would update it :)

**Comment by nidza07** [comment] 2024-01-04 23:34
@willwade The current version of the application works fine for me. Sometimes after the first installation it may take a few minutes for the voice to show though, but as long as you enabled the language you want inside VoiceOver languages section of the app, you should see the ESpeak voices under that language in either VoiceOver or spoken content accessibility settings, depending on what you want to use it for.

**Comment by XP-Fan** [comment] 2024-01-05 03:23
Totally unrelated but since I got those mails: Is there ESpeak NG for SAPI 5 actually?

**Comment by willwade** [comment] 2024-01-05 10:26
> @willwade The current version of the application works fine for me. Sometimes after the first installation it may take a few minutes for the voice to show though, but as long as you enabled the language you want inside VoiceOver languages section of the app, you should see the ESpeak voices under that language in either VoiceOver or spoken content accessibility settings, depending on what you want to use it for.

Well my bad! I do apologise! it is a bit, well flaky, at times. (it seems to work better in third party apps than apples own Speak Content settings..). Awesome stuff. Thanks :)
