### ISSUE TITLE
issues with georgian voice

### ISSUE THREAD

**Issue by beqabeqa473** [espeak-ng/espeak-ng#302] opened 2017-09-03 04:41 UTC
hello.

in the latest espeak numbers 3 and 7 in georgian voice are pronounced in english, also with some emojis computer is freezing unrecoverably, for example please read this line by character.

[■ ▶ ▮▮] ® Juventa, Erica Curran - Move Into Light (Koven Remix) ★ EXCLUSIVE! for club5485048 ★ [track at ➨ 04.11.2013] - Dubstep 4:22

what is the issue?

**Comment by beqabeqa473** [comment] 2017-09-11 03:54
hi, what can be done to fix this?

**Comment by jaacoppi** [comment] 2017-10-01 05:10
This is strange. I tried
espeak-ng -v ka "0 1 2 3 4 5 6 7 8 9" -x
and got:                                                                                                                                   "n'uli 'ert#i 'ori 'ot#xi x'ut#i 'ek#vsi rv'a ts#xr'a"

It seems that espeak-ng can't find _3 or _7 from ka_list. Reason is unknown.

espeak 1.48.03 speaks out _3 and _7. I'm not sure about the pronunciation.

**Comment by beqabeqa473** [comment] 2017-10-01 06:14
strange, why this could happen, it was all ok earlier and no
modifications have been made.

do you have ideas how to fix that?

On 10/1/17, jaacoppi <notifications@github.com> wrote:
> This is strange. I tried
> espeak-ng -v ka "0 1 2 3 4 5 6 7 8 9" -x
> and got:
>                                                               "n'uli 'ert#i
> 'ori 'ot#xi x'ut#i 'ek#vsi rv'a ts#xr'a"
>
> It seems that espeak-ng can't find _3 or _7 from ka_list. Reason is
> unknown.
>
> espeak 1.48.03 speaks out _3 and _7. I'm not sure about the pronunciation.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/302#issuecomment-333354067


-- 
with best regards beqa

**Comment by rhdunn** [comment] 2017-10-01 10:31
I've located the emoji entries that were causing this issue with speaking `3` and `7`, and have replaced them with the english versions. I have not identified the root cause of the issue, so am leaving this issue open.

**Comment by rhdunn** [comment] 2018-04-02 11:59
The root cause for this is the same as the freeze when pronouncing certain Tamil characters. Therefore, this is fixed by the fix for #332.

**Closed by rhdunn** 2018-04-02 11:59 UTC
Labels: bug, emoji
