### ISSUE TITLE
Please Improve the Thai Language 

### ISSUE THREAD

**Issue by HaapyFace** [espeak-ng/espeak-ng#757] opened 2020-05-21 21:30 UTC
https://en.wikipedia.org/wiki/Thai_language

**Comment by HaapyFace** [comment] 2020-05-21 21:33
Hey @valdisvi Please Add the Thai Language on eSpeak NG

**Comment by The1Freeman** [comment] 2020-05-22 01:39
You can do the work yourself, [it's documented too](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md)

**Comment by HaapyFace** [comment] 2020-05-22 14:09
I am not a programmer and Please Add the Thai language and Please Help me

**Comment by HaapyFace** [comment] 2020-05-26 20:29
I am not a Native Speaker Please add the Thai Language Please @valdisvi

**Comment by The1Freeman** [comment] 2020-05-26 21:41
Stop bothering him, he's not a native speaker as well and I've already linked to the documentation of how you can do it yourself.

**Comment by HaapyFace** [comment] 2020-05-27 03:42
@The1Freeman  I'm sorry to bother him but I will be happy you add this Language for the Blind People do not get angry please and can you please help me like The Poor People

**Comment by HaapyFace** [comment] 2020-05-27 12:00
@The1Freeman  sorry I cannot do myself but i try it but i don't know how to use your things but and can you help me please and by the way can you add Thai Language it will be interesting you add this language but i will to Test online please

**Comment by HaapyFace** [comment] 2020-05-27 12:13
@The1Freeman  i am not bothering him but angry with me and I am just Telling to Valdisvi

**Comment by boracasli98** [comment] 2020-05-29 20:28
I'm trying to create a Thai voice and I would like to change the positions of the consonants.

`espeak-ng -vth "ภาษาไทย" --ipa`
gives me:
`pʰaː4sˈaːa2jtʰ`
where it needs to be
`pʰaː4sˈaːtʰa2j`

**Comment by valdisvi** [comment] 2020-05-29 21:09
To "reorder" phonetic pronunciation regarding to writing, you have to consider all characters in the rule, something like this:

```
.group a
    abc  cba
```
You may use `pre)` or `(post` rules before/after character group, if you want to choose depending on them, but don't want to jump to next group of characters yet.
Also, if there is no canonical order for additional diacritic marks (like for Arabic vowels), you can make them in "canonical" order with `.replace` rule, e.g.:

```
.replace
    ca ac
    ā   ē
``` 
but currently you can replace only characters in groups, which together fit into 4 bytes (i.e. 2 ASCII letters to 2 ASCII letters, or 1 2-byte letter to 1 2-byte letter).

**Comment by HaapyFace** [comment] 2020-05-31 12:41
@valdisvi  I don't see the Thai language on the Demo odo.lv/Espeak can you add Please

**Comment by valdisvi** [comment] 2020-06-13 19:12
I have added initial support for Thai language. You can test it now on  https://odo.lv/Espeak.
Look for general guidance [here](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md#steps-for-your-contribution), and some specifics are following:

* Phonemes and voice tones are based on [Shan language](https://github.com/espeak-ng/espeak-ng/blob/master/phsource/ph_shan) many of tones are probably set wrong.
* Most of pronunciation rules in [th_list](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/th_list) and [th_rules](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/th_rules) are very simple just to hear something.

Good luck!

**Comment by boracasli98** [comment] 2021-01-19 00:54
Sorry for not creating a new issue. I'm making improvements to the Thai voice according to [this](https://en.wikipedia.org/wiki/Thai_script) but I have a problem with the tones.

For example:
ร is a low-toned letter, but when you add the "mai tho", it becomes high-toned.
Even if I write "r4u:" for "รู้", it keeps pronouncing it as "r2u:"

(th_rules)

tr_languages.c again?

Thank you.

**Comment by wannaphong** [comment] 2021-02-03 18:18
Can you add https://github.com/sr12zar/Espeak-ng-thai to Espeak-ng?

@sr12zar

**Comment by sr12zar** [comment] 2021-02-04 21:55
Hi,

I think 'espeak-ng' can include some of my modifications but I don't know
that espeak-ng can include 'g2p' part in a 'seamless way'.  I had tried
including the rules in 'g2p.awk' into th_rules of espeak-ng but abandoned
that due to lack of understanding of how espeak-ng processes the rules.
Perhaps a more espeak-ng savvy can help.

As you can see 'espeak-ng-thai' is just about a collection of free and
open-source tools we can use to build a tts system on Linux platform. I
name this toolset 'espeak-ng-thai' because I use espeak-ng as the speaker
and following the old proverb "ปากเป็นเอก", I place espeak-ng first.
We can use other synthesizers (not just  espeak-ng) as the speaker. I think
it is best to leave espeak-ng out of my 'meddling'.

sr

**Comment by yzl123456** [comment] 2022-03-11 08:47
I find some problems when using espeak-ng for thai language is that the output phoneme order is not correct, due to the writing order of thai language is different from the speak order of thai language, anyone find similar problems when using this for thai language? @0x5066 

And another one is that "[Espeak-ng-thai]" the project can solve the problem? thanks for your response @sr12zar

**Comment by jaacoppi** [comment] 2022-09-25 10:20
Closing as duplicate of #1092

**Closed by jaacoppi** 2022-09-25 10:20 UTC
