### ISSUE TITLE
Bishnupriya manipuri language

### ISSUE THREAD

**Issue by Giovani93** [espeak-ng/espeak-ng#353] opened 2017-12-10 10:26 UTC
Hi!
This language, which is known, as Bishnupriya manipuri is meitei language, which use also Bengali script.
I have noticed It on number, because those numbers had another origin, not Indoarian. Please, could You edit It in next version?
Thank You.
Marco Oros

**Comment by rhdunn** [comment] 2017-12-10 10:43
Duplicate of #238.

This has been fixed in #238 (and thus in the latest release) to use inc (Indic), from the issue you raised about it previously -- see https://github.com/espeak-ng/espeak-ng/blob/master/espeak-ng-data/lang/inc/bpy.

**Closed by rhdunn** 2017-12-10 10:43 UTC
