### ISSUE TITLE
More description needed, about choosing English accent in other projects that integrate eSpeakNG

### ISSUE THREAD

**Issue by shadyar** [espeak-ng/espeak-ng#258] opened 2017-05-10 09:42 UTC
@rhdunn 
#253 
it seams a good idea, just how about eg. NVDA user? (as you know, e-Speak-NG is integrated in this project)
I do not have any imagine, I would appreciate, if you could explain;which how do the Persian speakers will select English accent in NVDA project?
I should notify them, in time, because I publish a news-letter for users of e-Speak in Persian, the majority of them use NVDA.

**Comment by rhdunn** [comment] 2017-05-31 07:00
This is a duplicate of https://github.com/espeak-ng/espeak-ng/issues/216, like https://github.com/espeak-ng/espeak-ng/issues/253 was.

**Closed by rhdunn** 2017-05-31 07:00 UTC
Labels: resolved/duplicate
