### ISSUE TITLE
Please add Mongolian language

### ISSUE THREAD

**Issue by garawaa** [espeak-ng/espeak-ng#1935] opened 2024-06-22 13:52 UTC
Please add Mongolian language

**Comment by jaacoppi** [comment] 2024-07-27 15:18
Closing as a duplicate of #1324 and #1396 .

**Closed by jaacoppi** 2024-07-27 15:18 UTC

**Comment by btseee** [comment] 2026-09-02 10:07
Dear @garawaa,

I have been contributing Mongolian language support to this project for the past year and continue to actively develop and improve it.

Mongolian is a complex language, and the implementation is still not perfect, but I hope it will be useful and help move the project forward.
