### ISSUE TITLE
(Turkish) vocalization of words with double letters saying of one letters

### ISSUE THREAD

**Issue by destroyersboy** [espeak-ng/espeak-ng#668] opened 2019-10-03 19:59 UTC
Hello,

there has been some shortcomings in Espeak's Turkish voice synthesis for a long time.

The same letter can be found twice in some words in Turkish. (For example, [tr}tutturmak, elli)

Espeak say these words in a single letter. (tuturmak, eli)

I don't have enough C knowledge to develop Espeak. So I can only give information.

### Small information

This issue does not exist in version  eSpeak-2016.1.
I don't know Espeak's versioning system. I'm not sure of the values ​​I've given above, and if you have any questions, I'll try to help.
Starting from the old version, we can find out where the problem is from the changing Turkish files.

I apologize for inadequate English.
The topic is language, I would appreciate it if you simply write your answers. I don't understand complex sentences.

**Comment by hozosch** [comment] 2019-10-03 20:32
You mean that it should read double letters as just one? I would be able to fix that, but I don't know whether I'm right.

**Comment by destroyersboy** [comment] 2019-10-03 22:16
@hozosch 
Hayır.
duble harfli kelimeleri duble olarak okumalı. Bir değil.
Şu an tek olarak okuyor.
Espeak'ın yaptığı: tt > t, ll > l...
Olması gereken tt > tt, ll > ll...

Bütün harfler ve kelimeler için geçerli.

**Comment by destroyersboy** [comment] 2019-10-03 22:19
@hozosch 

No.
should read double letter words in double. Not one.
What Espeak does: tt> t, ll> l ...
It should be: TT> TT, ll> ll ...

Applies to all letters and words.

**Comment by hozosch** [comment] 2019-10-04 08:37
Ok, I can't reproduce this problem in espeak 1.49.3 dev. It is part of NVDA 2019.2 and it reads double letters as such.

**Comment by destroyersboy** [comment] 2019-10-04 14:15
Hi again,

nvda log:
```
NVDA version 2019.2.1

...

Using eSpeak NG version 1.49.3 dev
```


Double letters are read as one.
I suppose you said you didn't have this problem and it was working fine.
The problem continues.

Perhaps the problem is the bridge between NVDA and Espeak.
How else can I test Espeak?

If the problem is with NVDA, I can create an issue there.

**Comment by hozosch** [comment] 2019-10-04 14:53
No, for me, it's ok. It works fine with NVDA. Double letters are read as double letters. I think that is how you want it, isn't it? It's strange though that it isn't like that on your system. You can also test espeak on www.odo.lv/Espeak

**Comment by destroyersboy** [comment] 2019-10-04 15:23
Yes, I want the double letters to be read in double.

I tested many words on this site,
definitely problem.

Double letter pronunciations should be as in the old Espeak version 1.48.03.

Espeak 1.49.3dev To get old vocalization: I write: 'ettim' > 'etttim'.

Perhaps the emphasis on fortis should be increased. (tt dd...)

**Comment by hozosch** [comment] 2019-10-04 18:02
When I test "elli", I can't tell a difference in the both version. I get though what you mean now. Double t and stuff should be pronounced as two t consonants, instead of making a pause between them.

**Comment by destroyersboy** [comment] 2019-10-04 18:17
Yeah, there's nothing wrong with the word 'elli'. I must have accidentally added him as an example.

According to my tests: tt, dd, cc, bb, çç, dd, kk, pp...

**Comment by rhdunn** [comment] 2019-10-04 19:36
In #152 (released in 1.49.1 -- 2017-01-21), the double letters `tt`, `bb`, `cc`, `çç`, `dd`, `kk`, and `pp` were modified to use `_::p`, etc.

In #229 (released in 1.49.2 -- 2017-09-24), the long pause was modified to work better at higher speech rates. This (da3d534438398840af0f155fe3b01c630f9d34c5) should really be reverted and the code should be modified to better support higher speech rates, as there are other artefacts in all languages in this case.

I have some questions:
1.  Does 1.49.1 sound wrong as well?
2.  Is this a dialect difference between you and @burakyuksek (the person who raised #152)?

This is a process called [Gemination](https://en.wikipedia.org/wiki/Gemination). In the Turkish section, wikipedia transcribes the geminated consonants with a long consonant. That is:

    espeak-ng -xv tr "[[et:im]]"

This is how the Italian (`it`) voice handles gemination for the plosives. In that example, eSpeak still has a pause in the above before the `t`, but the pause is a lot shorter than the #152 version:

    espeak-ng -xv tr "[[e_::tim]]"

The original version:

    espeak-ng -xv tr "[[ettim]]"

sounds as if it has too much release on the first t (the exhilation of air after the initial closed part of the sound).

It might make sense to use the original `tt` variant, but modify the phoneme rules to make the first `t` an [unreleased stop](https://en.wikipedia.org/wiki/Unreleased_stop) making the geminated consonants `[t̚t]`. This is audible in the `en` voice for distinct consonants, like in the words 'apt' and 'doctor'.

@destroyersboy and @burakyuksek which of these is best for the both of you? Is using `[[t:]]`, etc. acceptable?

**Comment by destroyersboy** [comment] 2019-10-04 20:57
> In #152 (released in 1.49.1 -- 2017-01-21), the double letters tt, bb, cc, çç, dd, kk, and pp were modified to use _::p, etc.

I don't fully understand the purpose of the change here.
Q: kyu, w: dabılyu and x: iks.
That feedback is true.

I do not have the technical knowledge to interpret other technical parts and understand Espeak's phonetic syntax.

On the other hand, during fast reading and slow reading, double letters is emphasis and double,  not read as a single letter.
In the present Espeak, the double letters found above, are passed as singly.
It should be read and emphased in pairs.

> In #229 (released in 1.49.2 -- 2017-09-24), the long pause was modified to work better at higher speech rates. This (da3d534) should really be reverted and the code should be modified to better support higher speech rates, as there are other artefacts in all languages in this case.

@Burakyuksek said the error occurred as a result of the change.
The revision is reverted to version 1.48.03.
Because there's no problem here.

Not only at high speeds, but at slow speeds, exactly what the word is.

We can better understand this phonetic subject with the word 'eddard'.
In words where the letter D is double, the tension of the letter should not be lost.
This word is now read as 'edard'.
Letters like D and T should be emphasized more than this level.

> 1. Does 1.49.1 sound wrong as well?
Yes, Wrong:
> 1. Words that repeat a silent letter twice has the first instance of the letter muted. For example, in the word gitti, the first t needs to be muted.

The right lines:
> 2. The letters x, q and w are not pronounced correctly. X needs to be pronounced as iks rather than eks, w should be pronounced as çift v rather than duble v because duble is not a Turkish word, and the letter q needs to be pronounced as kyu rather than kve.

> 2. Is this a dialect difference between you and @burakyuksek (the person who raised #152)?  
No, no dialect difference. All Turkey, Istanbul Turkish speaks. This is the official.

**Comment by rhdunn** [comment] 2019-10-04 21:50
For 'd' and 'dd', does

    espeak-ng -xv tr "[[Ed'aRd]], [[Ed:'aRd]]"

or:

    espeak-ng -xv tr "[[Ed'aRd]], [[Edd'aRd]]"

sound better?

For 'sete sette' (made up), does:

    espeak-ng -v tr "[[s'ete]], [[s'et:e]]"

or:

    espeak-ng -v tr "[[s'ete]], [[s'ette]]"

sound better?

**Comment by burakyuksek** [comment] 2019-10-04 21:58
Hello,
I think espeak sounds fine the way it is, because for example when saying "ettim", we don't say 2 t's, we make the first t silent and say the second one. Of course when this first t is silenced, there is a slight pause. That's why I suggested that change.

**Comment by destroyersboy** [comment] 2019-10-04 22:50
Hello @rhdunn , I think we have found the solution.
espeak-ng -v tr "[[s'ete]], [[s'ette]]" and espeak-ng -xv tr "[[Ed'aRd]], [[Edd'aRd]]"

As @burakyuksek said, words like 'eddard' are broken.
More settings can be made for Turkish. But as it stands, it looks better.

I have friends who listen to books and write long articles with Espeak (15-20), I'm not happy with Espeak reading like a one letter.  
The thinks of my friends support my opinion.

I will work on Espeak's syntax. In the future, I'il help you with more.

I think that's the solution, we have to implement it.

**Comment by rhdunn** [comment] 2019-10-05 11:35
The ones you selected were the ones that @burakyuksek had an issue with in #152.

It would be better then to look at implementing the unreleased stop behaviour I mentioned above (like the English voice is doing for different consonant pairs in things like doctor) for the first of a geminated consonant pair and revert the doubled consonant change from #229 and #152

**Comment by destroyersboy** [comment] 2019-10-05 16:39
Hi @rhdunn again,

Frankly, I don't know exactly what you want to do. If you want to say that the pronunciation I'm talking about is incomplete and wrong, it is necessary to listen to Yelda, Nuance's Turkish voice.
https://www.nuance.com/omni-channel-customer-engagement/voice-and-ivr/text-to-speech.html#!
please write: "etti, appe, eddard"

Will you go back to **1.48.03**?

**Comment by rhdunn** [comment] 2019-10-05 17:51
If the sound go back to 1.48.03, then the issue reported in #152 would be present. I would like to modify it so that both this and #152 are fixed.

Notice that eSpeak sounds different to Yelda in with eSpeak you can clearly identify the consonant in both cases, but with Yelda the sound is much more subtle. That is what #152 was about, hence my reluctance to revert to the 1.48.03 behaviour without also fixing #152. As such, I would want to make both changes together.

I'm curious why you don't like the first version I listed, as using that in 'etti' sounds similar to the way Yelda is pronouncing it. That is also what the Italian eSpeak voice is doing for the geminated consonants.

## Details

It sounds like there is a glottal stop (or similar) for the first t or other consonant sound. It is like how in English you would pronounce something like 'set to', 'lamp post', or 'guard dog' in normal speech.

Experimenting with trying to produce those sounds compared to a glottal stop, it looks as if the following are happening with the first geminated consonant (and other unreleased stops):
1.  the tongue is in the position of the stop being produced, not the position of a glottal stop;
2.  the glottis is closed to prevent air escaping;
3.  the mouth is closed in the `p` sound (like it is in the regular version before the release part of that sound);
4.  the initial closure phase is held a fraction longer in the geminated version of a consonant than the non-geminated version. NOTE: This also applies for the nasal consonants like `n` (e.g. in the Italian 'anno') where the tongue is held at the roof of the mouth for a fraction longer than the non-geminated version.

I'm not sure how to achieve this in eSpeak, so some experimentation would be needed. I'm also not sure if a regular glottal stop would be sufficient in this instant. The eSpeak glottal stop is not great, so would need improving.

I'm also not sure if code changes (in addition to pronunciation rule changes) would be needed.

**Comment by rhdunn** [comment] 2019-10-05 18:00
I've made the change to use the long consonants, like in the Italian gemminated consonants. For 'etti', this sounds very close to the sound that Yelda makes in the Nuance voice, and there is a difference between 'eti' and 'etti'.

**Comment by destroyersboy** [comment] 2019-10-05 18:33
At the moment there seems to be no problem with Turkish synthesis.
I compiled immediately after the change.

Moreover, in the pronunciation of double letters, there was no contradiction to the Turkish language rules and emphasis.

**Comment by rhdunn** [comment] 2019-10-05 19:12
So this is fixed now?

**Comment by destroyersboy** [comment] 2019-10-05 19:56
Hey, I need some scrutiny.

I'm gonna talk to people with more Turkish grammar and emphasis.
We don't want to do anything wrong, do we?

We can add changes to a new branch.
When the tests are over, we get them to the master.

**Comment by rhdunn** [comment] 2019-10-05 20:02
Sure. You could also clone the repository and make the changes in your cloned version of espeak.

**Comment by destroyersboy** [comment] 2019-10-16 18:15
Hello, nice change.
Long term test result successful.

Lots of love.

**Comment by rhdunn** [comment] 2019-10-16 18:19
Great. Thanks for taking the time to test it.

**Closed by rhdunn** 2019-10-16 18:19 UTC
