### ISSUE TITLE
Chinese Mandarin: English words pronunciation problem

### ISSUE THREAD

**Issue by surfer0627** [espeak-ng/espeak-ng#347] opened 2017-12-06 02:17 UTC
Hi,
This case occurred in Chinese Mandarin.

### Steps to reproduce:
1. Open [testing page](http://odo.lv/Espeak?language=en).
2. Choose language Chinese Mandarin.
3. Type.
> English literature

### Expected behavior: 
ESpeak NG reads English words correctly.

### Actual behavior:
It is difficult to understand the pronunciation.
Pronunciation
English America: 'INglIS l'It#3rI#tS3
Chinese Mandarin: 55Nl'i55s._| l,i55th@55z.,A55thu55z.'o-55_

CC: @valdisvi

**Comment by jiangtiandao** [comment] 2018-06-07 10:47
pinyin is rarely used in daily communication in Chinese.
Almost all latin char is english text

**Comment by rhdunn** [comment] 2018-06-07 12:31
Pinyin is used internally by eSpeak to handle the Chinese pronunciations -- these are derived from the Unihan data in the Unicode Character Database (e.g. mapping 萄 to `tao2`). The pinyin is then mapped to the underlying IPA phonemes with tones using an ASCII transcription based on Evan Kirshenbaum's ASCII IPA.

The tone markers are for the start and end tones (if 2 numbers are specified), or start, middle, and end tones (if 3 numbers are specified). They range from 1 (low) to 5 (high), so `55` represents a high level tone, `53` a high to medium falling tone, and `153` a low to high to medium rising-falling tone.

This is related to #216.

- [ ] I agree that there should be a `zh-Latn-pinyin` language file that only handles the Latin characters, and pronounces them using the pinyin rules (like in the current Chinese file).
- [ ] The Chinese language should internally bind the pinyin translations to `zh-Latn-pinyin` (e.g. `$textmode zh-Latn-pinyin`), such that it does not override the user specified or default language used for Latin characters.
- [ ] The pinyin support in the Chinese language file should be removed once the above functionality has been implemented.

This is complex to fix due to the way espeak currently works internally.

**Comment by jaacoppi** [comment] 2022-09-24 04:47
Duplicate of multiple tickets. See #1370 for newer discussion. Closing.

**Closed by jaacoppi** 2022-09-24 04:47 UTC
