### ISSUE TITLE
Making e-speak Russian voice speak in another language than English

### ISSUE THREAD

**Issue by fatihyuksek1** [espeak-ng/espeak-ng#889] opened 2021-03-06 20:15 UTC
I would like to make e-speak Russian voice read Latin characters in Turkish instead of English. How could this be possible?

**Comment by jaacoppi** [comment] 2021-03-07 10:53
For a quick and dirty hack:
Add line `"new_language="tr;"` right before this line:
https://github.com/espeak-ng/espeak-ng/blob/6a43f8c9849da6dd2a8b20fc2acc927b7a75ddf4/src/libespeak-ng/translate.c#L1495

Another solution might work ase well: use dictrules 1 in language file and ?1 a _^_tr for each alphabet like cantonese does. See https://github.com/espeak-ng/espeak-ng/issues/347

Let me know if you are satisfied with either solution.

For a long term solution, there should be a way to set a default fallback language. alt_alphabet and alt_alphabet_lang seem to be made for that purpose but I didn't get them to work correctly.

**Comment by fatihyuksek1** [comment] 2021-03-07 20:37
Hello,I am not a developer, so can’t understand this code. I was looking for this solution while using e-speak ng with NVDA. I don’t know how to save this file or where should I copy it in NVDA.Thanks Windows 10 için Posta ile gönderildi Kimden: jaacoppiGönderilme: 7 Mart 2021 Pazar 13:53Kime: espeak-ng/espeak-ngBilgi: Fatih Yüksek; AuthorKonu: Re: [espeak-ng/espeak-ng] Making e-speak Russian voice speak in another language than English (#889) For a quick and dirty hack:Add line "new_language="tr;" right before this line:https://github.com/espeak-ng/espeak-ng/blob/6a43f8c9849da6dd2a8b20fc2acc927b7a75ddf4/src/libespeak-ng/translate.c#L1495Another solution might work ase well: use dictrules 1 in language file and ?1 a _^_tr for each alphabet like cantonese does. See #347Let me know if you are satisfied with either solution.For a long term solution, there should be a way to set a default fallback language. alt_alphabet and alt_alphabet_lang seem to be made for that purpose but I didn't get them to work correctly.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jaacoppi** [comment] 2021-03-08 13:42
Basically, you would need to:
1. download espeak-ng windows binary
2. edit espeak-ng-data/lang/zle/ru to include line "dictrules 3" (3 because 1 and 2 were in use already)
3. include these lines for each alphabet (a to z) in dictsource/ru_rules:
.group a
?3   a   _^_TR

4. run espeak-ng --compile=ru to create a new ru_dict file with your changes
5. Replace the ru_dict file that comes with NVDA. It's probably in C:\Program Files (x86)\NVDA\synthDrivers\espeak-ng-data

I attached a sample file for you. I think it works but since you can try and see. Remember to backup your existing ru_dict before overwriting it.

[ru_dict.zip](https://github.com/espeak-ng/espeak-ng/files/6101684/ru_dict.zip)

**Comment by jaacoppi** [comment] 2022-09-25 08:41
Duplicate of #999

**Closed by jaacoppi** 2022-09-25 08:41 UTC
