### ISSUE TITLE
Where/How to get a full list of phone set used for each language?

### ISSUE THREAD

**Issue by XuesongYang** [espeak-ng/espeak-ng#1216] opened 2022-06-16 03:45 UTC
I am using this backend to make a G2P-like conversation. But I did not know where to find a complete list of the phone set for each language. Could anyone share the approach to getting the language-specific phone set used by Espeak? Thanks.

**Comment by jaacoppi** [comment] 2022-09-25 05:43
Closed as a duplicate of #1050

**Closed by jaacoppi** 2022-09-25 05:43 UTC
